# Site settings
title: Across the Ocean
description: Best music albums of all time. Psychodelic, Progressive, avant-garde etc
keywords: Music, Psychodelic, Progressive, avant-garde, experimental, albums
author: Eugene, Kirill
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
